### ISSUE TITLE
/dataset/Semval/train.txt 文件

### ISSUE THREAD

**Issue by JewelYueng** [ShomyLiu/pytorch-pcnn#3]
请问一下，这个文件是经过了什么处理得到的呢

**Comment by ShomyLiu** [comment]
我记得应该就是原始的数据，

**Comment by JewelYueng** [comment]
我在原始的数据里面没有找到这个文件。。不过还是很感谢你的解答

**Comment by failable** [comment]
请问这份数据的出处是？最原始的数据应该是：https://docs.google.com/document/d/1QO_CnmvNRnYwNWu1-QCAeR5ToQYkXUqFeAJbdEhsq7w/preview
这里的。dataset/SemEval里经过预处理的出处是？我想知道词汇表预处理这些相关的参数设置。
