### ISSUE TITLE
semeval.py

### ISSUE THREAD

**Issue by XAKK** [ShomyLiu/pytorch-pcnn#6]
https://github.com/ShomyLiu/pytorch-pcnn/blob/0f135e8146ebbd9ce5c6c89f7e693b5a29586972/dataset/semeval.py#L190

It seems should be
`pos_right = pos_right[: self.max_len]`
How strange that I got a lower F1-score if I change it.

**Comment by ShomyLiu** [comment]
It indeed should be 
```
pos_right = pos_right[: self.max_len]
```
When I try the right codes above, I have obtained a slightly better results `81.14->81.58`, 
However, it still seems that the impact is very slight...

Besides, would you mind pulling a request for this bug ？
